### ISSUE TITLE
move continuation return-type to macro (pragma syntax)

### ISSUE THREAD

**Issue by disruptek** [disruptek/cps#20]

**Comment by zevv** [comment]
So this means

```
proc foo(): Cont {.cps.}
```

will become

```
proc foo(): {.cps: Cont.}
```

right?

**Comment by disruptek** [comment]
Eventually, it becomes `proc foo(c: Cont): SomeResult {.cps: Cont.}` right?

So maybe it is just immediately `proc foo(c: Cont): SomeResult {.cps.}` instead?
