### ISSUE TITLE
can I haz .cps. blocks

### ISSUE THREAD

**Issue by zevv** [disruptek/cps#209]
In my cpstest project I find myself typing files with mostly cps procs, so I need to repeat the `{.cps:Cont.}` for every proc over and over again.

In the early life of cps, we had a block syntax that transformed all procs in a block. This was dropped when the cps macro became typed. Would it be possible to make something like below, where all ProcDefs in the block are transormed as if they were given the `.cps.` pragma?

```
cps C:
  proc foo() =
    echo "foo"
  proc bar() =
    foo()
  bar()
```

will mean the same as

```
cps C:
  proc foo() {.cps:C} =
    echo "foo"
  proc bar() {.cps:C} =
    foo()
  bar()
```

**Comment by disruptek** [comment]
Sure.  So how does `cps:` work?  Shouldn't it just put you in an adhoc `Continuation`and we transform all procdefs in scope?  What else would it do?

But then you have to save it as a lambda or something, right?

Maybe what it does is it's just sugar for a CPS proc that is immediately invoked.

**Comment by zevv** [comment]
It says in the example: `cps C:` transforms all the procs in the macro as if they were individually passed `{.cps:C.}`

**Comment by disruptek** [comment]
That's a waste of `cps:` syntax.

**Comment by zevv** [comment]
macros with the same name should do the same thing. less surprises.

**Comment by disruptek** [comment]
By that rationale, we should only have `cps` transform a single procedure.  Sounds like you can close the issue.
