### ISSUE TITLE
Getting rid of reallocs

### ISSUE THREAD

**Issue by zevv** [disruptek/cps#27]
Just writing this up because I'm still not sure if we're thinking the same thing.

## How stuff works now

Some things I think are true:

- We have a proc that gets split up into a number of continuation procs.

- For each of these split procs, a dedicated environment object type is generated.

- An environment for a deeper nested scope inherits its parents environment.
  This is now done with Nim inheriting objects, but this could also be done by
  embedded parent environment objects as the first member of the child
  environment, or by making all these environments "from scratch" but taking
  care they for a proper tree hierarchy

Practical example:

The pre-transform original proc:

```
proc foo(a: int): Cont {.cps.} =
  echo "a = ", a
  var i: int = 0
  while i < 5:
    echo "i = ", i
    inc i
    inc a
  var j: int = 0
  while j < 5:
    echo "j = ", j
    inc j
    inc a
  echo "a = ", a
```

These are the generated environment types:

```
type
  env0 = ref object {.cpsLift.}of Cont
    a: int

type
  env1 = ref object {.cpsLift.}of env0
    j: int

type
  env2 = ref object {.cpsLift.}of env0
    i: int
```

In memory, these will look like this:

```
             ---
  @ 0x00:   | a | env0
             ---

           ------------
	  |  ---       |
  @ 0x00: | | a | env0 |
          |  ---       | env1
  @ 0x08: |   i        |
           ------------

           ------------
	  |  ---       |
  @ 0x00: | | a | env0 |
          |  ---       | env2
  @ 0x08: |   j        |
           ------------
```

Because `i` and `j` are never active at the same time but only in two
successive scopes, they will occupy the same location in `env1` and `env2`.

This is what one of the split procs now looks like:

```
 1 proc brake(locals: Cont): Cont =
 2   let a: int = env0(locals).a
 3   block:
 4     block:
 5       var j: int = 0
 6       inc a
 7       return Cont(env1(fn: loop, j: j, a: a))
 8     return Cont(env0(fn: tail, a: a))
```

- At line 2 variables are pulled out of the environment into a local variable
- At line 6 and 7 a new environment for the next continuation is allocated, and the
  current locals are copied into the new environment

## Problem statement

The problem we have now is that ever continuation gets a new, freshly allocated
environment. That's one alloc per trampoline call, which gets out of hand
quickly. Also, data get copied in and out environments for each call.

Aso, we can not simple rewrite local variables to environment access (`i` ->
`env.i`), since the (potentially modified) variables need to be copied into the
next environment just before the return.

## Solution?

The solution would be to alloc one single block for the environment, and reuse
this block as it is passed between continuations. During collection of the
enviroment the maximum possible environment size can be calculated, which is
used as the initial alloc size.

- Don't copy locals out of the incoming environment, instead rewrite the code
  to use the vars from the env
- Convert/cast the passed env to the next type, update the members that need
  updating and pass that block to the next continuation

```
 1 proc brake(locals: Cont): Cont =
 2   block:
 3     block:
 4       var j: int = 0
 5       inc (env0(locals)).a
 6       result = cast[env1](locals)
 7       result.fn = loop
 8       result.j = j
 9       return result
10     result = env0(locals)
11     result.fn = tail
```

- Line 6 casts the incoming env to the next type 'env1'. We can not use a
  convert here since we might need to reuse the data for incompatible branches in
  the inheritance tree (where different members occupie the same address)
- Line 7 and 8 update the parts in the environment that need updating. Note that
  `a` is already in the right place as received from the incoming env

## Optimizations

- Instead of allocating the maximum possible size of the env of this chain of continuations, we could start small and
  realloc only when needed.

**Comment by disruptek** [comment]
I guess I see what you mean now; you want to cast to all the different types as you move through the goose.  I was simply folding types to make a single type holding all the fields.  The problem with your version is that we're screwed if the field order changes.  Also, why not just initialize `cast[env1](locals).j` instead of creating it on the stack?

But, we are basically at the point in #26 where we can reuse the env in many/most cases, and without a cast.  One reason we had to create the object in a single expression was requires-init fields.  So that's not a thing anymore in this scenario.

Also, in theory, `result` is a gensym'd field with a normal value.  It just changes its location in the env when the return value changes.

**Comment by zevv** [comment]
Making a simple type holding all the fields is porobably simpler, but the downside is that you are all the time also carrying stuff around that is not in your current scope, you can not reuse part of the env that you left behind you.

**Comment by zevv** [comment]
Essentially, the environment will be bigger then the max stack size ever should have been if the proc was not chopped up.

**Comment by zevv** [comment]
But sure, let's see what #26 will bring!

**Comment by disruptek** [comment]
I'm too lazy to draw a picture, but to give you an idea of what craziness #26 enables, subsequent continuations can change not just the variables in the environment, but also the `result`, the `function`, and the `exception` of a prior continuation.  Of course, you can use any of these values above the scope where they are nominally "created".

_**mindfuckery intensifies**_

**Comment by zevv** [comment]
Reopening because I had a very trivial insight, which might make more sense then all the above drawings: The environment of any continuation should be exactly the same as the stack frame that would exist at that point before the continuation.

I feel kind of stupid that I had to sleep a night to discover that.

Anyway, the current implementation looks pretty slick, let's go with that first!

**Comment by disruptek** [comment]
I thought about this a bit more, too.

- The input to CPS **MUST** be typed.
- Now we know the object composition and the alignment.
- Also avoids generics, which means better typing.
- Inference, tuples, etc. all work.
- cpsMagic is no longer a thing
- Lets us scale the continuation arbitrarily, even at runtime.
- This arbitrary scaling begets custom memory management per continuation.

I am working on a different approach to the env in which we simply track the scope.  It will probably make much more sense (more correct) and should make the type issue easier; once that works, we have a really powerful design.

Also, I have no internet.

**Comment by zevv** [comment]
Right, this all makes good sense. I guess we had to go through all this first to learn & realize all that.

Do you recall why exactly this stuff ended up to be untyped in the first place? 

Also, for a man without internet you do a good job reading and writing things on, like, the internet.

**Comment by disruptek** [comment]
Well, the Internet here is sporadic and I mostly had around 85% packet-loss today, so I walked in to town to type on my phone.  :grin:

One reason we were `untyped` was that the syntax varied inside and outside of continuation context, and I really wanted to produce friendly error messages to avoid the confusion people have with `await` versus `waitfor`.  But, as per #28 -- I'm increasingly unworried about syntax.

My solution to the problem of special treatment for the originating continuation proc is to write a new one that instantiates the environment and then continues on merrily with all the usual assumptions.  This lets us centralize an exception handler, for example, or pre-alloc, or whatever.  Mostly, though, I expect this stuff to get a lot simpler and require much less intervention on our part -- it will just work.
