### ISSUE TITLE
shim try expressions

### ISSUE THREAD

**Issue by disruptek** [disruptek/cps#43]

**Comment by alaviss** [comment]
Not sure what this is, is it deprecated by flattening?

**Comment by disruptek** [comment]
Maybe.

```nim
let x = try:
  "foo"
except:
  "bar"
```

...or whatever.

**Comment by alaviss** [comment]
Already done and tested:

https://github.com/disruptek/cps/blob/a1d3a926c6cde75034a35318ac481879a84c42ad/tests/texprs.nim#L102-L127
