### ISSUE TITLE
mutable params and the developers who love them

### ISSUE THREAD

**Issue by disruptek** [disruptek/cps#47]
At some point I developed the conceit that this test should work.  The question is whether @Clyybber and company are going to put the kibosh on this due to some hidden addr bs.

```nim
    block:
      ## reassignment of var proc params
      ## https://github.com/disruptek/cps/issues/22 (2nd)
      proc foo(a, b, c: var int) {.cps: Cont.} =
        a = 5 
        noop()    
        b = b + a
        noop()   
        check:  
          a == 5
          b == 7
          c == 3
      var (x, y, z) = (1, 2, 3)
      trampoline foo(x, y, z)
      check:
        x == 5
        y == 7
        z == 3
```

**Comment by alaviss** [comment]
I've tested the resulting transform with manual changes to use `views` + storing `var int` in `env`. The result is SIGSEGV. We can't support this until the compiler gain proper views support.
