### ISSUE TITLE
shadowed variables don't work due to name clashes

### ISSUE THREAD

**Issue by disruptek** [disruptek/cps#9]

**Comment by disruptek** [comment]
What's really lovely about this is how the behavior changes with `--define:cpsCast`. :roll_eyes:

**Comment by zevv** [comment]
Quoting Andy Davidoff (2020-07-27 06:16:09)
> What's really lovely about this is how the behavior changes with `--define:cpsCast`. :roll_eyes: 

yes but no but yes but

**Comment by zevv** [comment]
I'm quite curious what the practical differences would be for casting vs converting in something like the below snippet:

```
type

  T1 = ref object of RootObj
    name: string

  T2 = ref object of T1
    age: int

# Create instance of derived type
let v1 = T2(name: "T2", age: 8)

# Convert to parent type
let v2 = cast[T1](v1)

# Convert back to original type
let v3 = cast[T2](v2)

```

I do see  that the codegen is different for those cases, but I'm not able to come up with a minimized program that would actually be able to tell if `v2` or `v3` were casted or converted.

**Comment by zevv** [comment]
http://ix.io/2sqi
